FROM jenkins/jenkins:lts-jdk17

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg \
        lsb-release \
        docker.io \
        docker-cli && \
    rm -rf /var/lib/apt/lists/* && \
    ln -sf /usr/bin/docker /usr/local/bin/docker

RUN usermod -aG docker jenkins

USER root
